### ISSUE TITLE
Add harmony brush

### ISSUE THREAD

**Issue by Ygarr** [lbalazscs/Pixelitor#11]
Please add if possible brush with extra feature like in harmony project. Pic related
![2018-08-07-023842_1187x926_scrot](https://user-images.githubusercontent.com/14309871/43746153-39068260-99eb-11e8-8556-16a325a7b657.png)

Link of inspiration: http://www.java-gaming.org/topics/what-i-did-today/33622/view.html

**Comment by Ygarr** [comment]
Here is sources ( from first links)
http://www.java-gaming.org/index.php?action=pastebin&hex=c6f303c8392

**Comment by lbalazscs** [comment]
Thanks, this is a very cool looking effect! I definitely plan to add this.

**Comment by lbalazscs** [comment]
It is in the Github-pushed version now, as the "Connect" brush. Best used with the "Lazy Mouse" feature, which is also new. 
![pix_screenshot](https://user-images.githubusercontent.com/9939454/44006430-9a732b32-9e84-11e8-9aa8-36779e29a959.png)

**Comment by Ygarr** [comment]
Thanks a lot!

**Comment by Ygarr** [comment]
Much gratitude!
