### ISSUE TITLE
Add option for mouse wheel zoom as default

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#132]
I have recently used Pixelitor for a lot of image editing and as I've mentioned before I really like it for all sorts of reasons - especially due to polish and attention to small practical details. It's simply really nice to work with.

There is one thing that I keep stumbling on though. Most other programs I use, tools like Inkscape, Blender, Godot, etc use Mouse Wheel for Zooming as default, without the need to hold down a key. I find this workflow very practical since I zoom in and out of parts I work on much more often than I scroll up/down. That combined with Middle-click to pan around feels very practical to me. So I was wondering if it would be possible to add an option in Pixelitor to use the mouse wheel to zoom by default?

**Comment by lbalazscs** [comment]
Hi Imerion,

The good news is that I implemented this in the newest GitHub version.

![mouse_wheel_setting](https://user-images.githubusercontent.com/9939454/95242401-66f81c80-080f-11eb-8ee0-9afa64affe27.png)

The bad news is that I don't plan to release a new Pixelitor version in the near future, so you will have to build it yourself from the current source code, as described here: https://github.com/lbalazscs/Pixelitor/blob/master/Developing.md

It shouldn't be very difficult to build it. If you need any help, please open a new issue. Note that while the last released version requires Java 8+, the current version requires Java 15+, so you might have to upgrade Java to the newest OpenJDK.

**Comment by Imerion** [comment]
Wow, thanks! That was quick! I am really grateful. I have managed to build Pixelitor before, so that shouldn't be a problem. My Linux distribution currently only comes with OpenJDK 14, though it seems it will be upgraded in the next release that comes out in a month, so that is fine.

**Comment by lbalazscs** [comment]
https://adoptopenjdk.net are supposed to have OpenJDK 15 packages for Debian, Ubuntu, Centos, RHEL, Fedora and SUSE, as described at https://adoptopenjdk.net/installation.html?variant=openjdk15&jvmVariant=hotspot#linux-pkg

(I don't have experience with these packages, but I found adoptopenjdk pretty reliable in the past)

**Comment by Imerion** [comment]
Good tip, I'll check that out!
