### ISSUE TITLE
Add option for middle-click pan

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#133]
In relation to my other Issue #132 it would be very nice to be able to hold Middle Click to pan around the drawing.

**Comment by lbalazscs** [comment]
Implemented in the GitHub version, about releasing see #132 

![pan_setting](https://user-images.githubusercontent.com/9939454/95296637-66946b80-0879-11eb-95bd-5b7910b1729c.png)

**Comment by Imerion** [comment]
Fantastic! Again, a big thanks!
