### ISSUE TITLE
Will Pixelitor ever have the ability to save filter presets?

### ISSUE THREAD

**Issue by superdreamkilla** [lbalazscs/Pixelitor#135]
The Gimp has the ability to save presets of filters for easy reaccess and direct modification. 
(gimp 2.10.20 exhibiting Spiral filters)
![image](https://user-images.githubusercontent.com/61440491/96046894-be2b6c00-0e63-11eb-9f85-b09523a62441.png)

Pixelitor has many more filters then gimp that contain a lot more options. However it does not have the ability to save presets (as I currently know)
![image](https://user-images.githubusercontent.com/61440491/96047220-4d388400-0e64-11eb-9ba5-d5a6e039ae56.png)

If there was some kind of preset option it would be nice, Maybe Pixelitor could copy the settings into a clipboard manager  and then the user can save a text file of the preset to paste it back into Pixelitor to enact the filter. 

Here is a pathetic mock up I made
![image](https://user-images.githubusercontent.com/61440491/96048369-077cbb00-0e66-11eb-8c42-26186dd1aa51.png)

**Comment by lbalazscs** [comment]
This shouldn't be difficult to implement, because there is already a mechanism for saving and restoring the current state of a filter (this was already needed by the tweening animation). I will look into it in the next few days.

**Comment by lbalazscs** [comment]
The newest GitHub version should be able to save and remember filter presets (for almost all filters). They are saved as editable text files: if you save a preset, then a "Manage Presets..." menu also appears, which opens the file manager for the presets folder, where you can delete or edit the preset files.

**Comment by superdreamkilla** [comment]
Ah, This is great! My workflow needs for pixelitor are complete.

I just noticed that filters relating to creating gifs in 
>file >export tweening animation  

do not make use of the preset templates. It would be a good idea to incorporate presets there if possible. Gifs/short videos like that aren't part of my workflow but I can imagine  someone benefiting from it.

**Comment by lbalazscs** [comment]
Indeed, the presets would be very useful for the tweening animation (and also for the batch filtering), I plan to implement them. Thank you for your feedback and let me know if you have other ideas in the future or if you find bugs.
