### ISSUE TITLE
Pop-up errors in batch filter box blur

### ISSUE THREAD

**Issue by PozhidaevYury** [lbalazscs/Pixelitor#136]
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
Pixelitor 4.2.3
MacOS Catalina 10.15.7
Java Version 1.8.0_252

Pop-up errors after processing each file.

Step to reproduce:
1. Create some images.
2. File -> Automate -> Batch filter.
3. Select Box blur filter.
4. Specify the image storage folder.
5. Click Next button.
6. Click Start Processing button (don't change radius).

Expected result: saving files to the selected folder.
Actual result: pop-up error message while processing each file.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/43886351/97100913-3ba87500-16cb-11eb-9d23-2c823c3f854a.png">

**Comment by PozhidaevYury** [comment]
Upd. Same problem exists with the filter Brithness/Contrast.

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/43886351/97101236-46b0d480-16ce-11eb-90b8-29e701da9405.png">

**Comment by lbalazscs** [comment]
Thank you for reporting this bug! It is now fixed in the GitHub version.

**Comment by lbalazscs** [comment]
The fix is included in the 4.2.4 beta 1: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1

**Comment by lbalazscs** [comment]
The fix is included in the final 4.3.0, which was just released.
