### ISSUE TITLE
All previously selected colors in the palette are marked

### ISSUE THREAD

**Issue by PozhidaevYury** [lbalazscs/Pixelitor#137]
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
Pixelitor 4.2.3
MacOS Catalina 10.15.7
Java Version 1.8.0_252

1. Create some image.
2. View -> Color Palette.
3. Choose any color.
4. Choose another color. 

Expected result: only the selected color is marked.
Actual result: All previously selected colors in the palette are marked.

<img width="355" alt="image" src="https://user-images.githubusercontent.com/43886351/97160749-623fdc00-17af-11eb-9fae-770a1775b92a.png">

**Comment by lbalazscs** [comment]
Thank you for reporting this, but I consider this a feature, not a bug... The purpose of marking of visited colors is to help the user remember which colors were already tried. Without the marking it happens that I know that I found a good color a few clicks ago, but I can't remember which one it was.

Perhaps it would be an improvement to mark the last color differently than the others.

**Comment by lbalazscs** [comment]
Implemented in GitHub (the last selected color is marked in a different way as well, with a stronger 3D-raised effect).

**Comment by lbalazscs** [comment]
The implementation is included in the 4.2.4 beta 1: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1

**Comment by lbalazscs** [comment]
The implementation is included in the final 4.3.0, which was just released.
