### ISSUE TITLE
Pop-up error message when trying to check updates

### ISSUE THREAD

**Issue by PozhidaevYury** [lbalazscs/Pixelitor#138]
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
Pixelitor 4.2.3
MacOS Catalina 10.15.7
Java Version 1.8.0_252

Step to reproduce:

1. Open app.
2. Help -> Check for Update.

Expected result: checking for a new version or notification that there are no updates
Actual result: pop-up error message.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/43886351/97261943-7983d580-1852-11eb-9158-3d8cf5a016a5.png">

**Comment by lbalazscs** [comment]
Thank you for reporting this bug! It is now fixed in the GitHub version.

**Comment by lbalazscs** [comment]
The update check is fixed in the just released version 4.3.0
