### ISSUE TITLE
Black dots when using a brush with a radius of 1 to 3

### ISSUE THREAD

**Issue by PozhidaevYury** [lbalazscs/Pixelitor#139]
Reproducibility: Always
Severity: Minor
Priority: Medium
Software:
Pixelitor 4.2.3
MacOS Catalina 10.15.7
Java Version 1.8.0_252

Step to reproduce:

1. Create some image.
2. Select Brush Tool.
3. Set the parameter radius to 1 or 3.
4. Create any object in the layer.

Expected result: created an object of the selected color
Actual result: created an object with black points. The dots disappear when you hover the mouse over them  

<img width="980" alt="image" src="https://user-images.githubusercontent.com/43886351/97263689-1a27c480-1856-11eb-9758-2cc16c18c311.png">
<img width="965" alt="image" src="https://user-images.githubusercontent.com/43886351/97263780-417e9180-1856-11eb-9438-64fe99d082db.png">

<img width="963" alt="image" src="https://user-images.githubusercontent.com/43886351/97263740-2f9cee80-1856-11eb-86b7-aeb36ddb5e3b.png">

**Comment by lbalazscs** [comment]
Thank you for reporting this bug! It is now fixed in the GitHub version.

**Comment by lbalazscs** [comment]
The fix is included in the 4.2.4 beta 1: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1

**Comment by lbalazscs** [comment]
The fix is included in the final 4.3.0, which was just released.
