### ISSUE TITLE
G'MIC and Pixelitor?

### ISSUE THREAD

**Issue by superdreamkilla** [lbalazscs/Pixelitor#141]
![image](https://user-images.githubusercontent.com/61440491/97647798-0b563300-1a4b-11eb-8d6c-770313268b57.png)
https://gmic.eu/
G'MIC is a popular free and open source image processing tool that works with Gimp and Krita. It has many filters. I was wondering if it could be setup to work with Pixelitor?

Here is a spoof I made of what it would look like (except GMIC usually occupies full screen)
![image](https://user-images.githubusercontent.com/61440491/97647107-4eafa200-1a49-11eb-8615-e3fedefe05b8.png)

Gimp is GTK2 software and yet it is still able to interact with QT based G'MIC and G'MIC always opens in a window of it's own separate from Gimp and Krita, It can even be ran isolated in a CLI. To get G'MIC working on Gimp and Krita the user has to manually tell them where to locate the G'MIC binary. If Pixelitor were to integrate with GMIC, it would have to instruct the user to locate the G'MIC binary that it needs.

Binary of G'MIC
![image](https://user-images.githubusercontent.com/61440491/97647719-e19d0c00-1a4a-11eb-8c4d-4e4e6e6fc170.png)

Thanks.

**Comment by lbalazscs** [comment]
Yes, I know about G'MIC, and I agree that it would be nice to integrate it with Pixelitor, but there are technical issues. Pixelitor currently is written in 100% Java, but G'MIC is written in C++. It is not impossible to call code written in C++, but it would introduce a lot of complexity. I do plan to use C++ libraries, but not in the near future, especially considering that there are ongoing efforts now to improve Java in this regard (see https://openjdk.java.net/projects/panama/) - I expect that in 1-2 years it will be easier to use C/C++ from Java.

**Comment by LinuxBeaver** [comment]
We can close this now as GMIC is in Pixelitor.
