### ISSUE TITLE
Suggestions/feature request for Pixelitor's text caption 

### ISSUE THREAD

**Issue by superdreamkilla** [lbalazscs/Pixelitor#148]
It would be nice of we can outline text easily. I know it's possible using Enabled and Inner Color on the Neon Border setting. But if there was a fifth option to outline. Things would be a lot easier. Another idea would be to have text presets similar to filter presets.  

Pic related
![image](https://user-images.githubusercontent.com/61440491/104137464-c3ca1c80-5394-11eb-8a80-b4f7e427a33a.png)

**Comment by lbalazscs** [comment]
I think text presets would be a great idea!

**Comment by lbalazscs** [comment]
Text presets are now implemented in the GitHub version.

**Comment by lbalazscs** [comment]
The implementation is included in the 4.2.4 beta 1: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1

**Comment by lbalazscs** [comment]
Text presets and other presets are included in the final 4.3.0, which was just released.
