### ISSUE TITLE
Select background color in Starburst filter.

### ISSUE THREAD

**Issue by LinuxBeaver** [lbalazscs/Pixelitor#164]
The starburst filter allows me to select the foreground color but not the background color.  Unless I have prechoosen and selected "Tool background."  I tried clicking on the tool  background color to change it in real time but it wouldn't let me while the Starburst dialog was open.

Could there be a way to edit the background color of starburst?

**Comment by lbalazscs** [comment]
In the newest GitHub version the background is a simple color selector, and it's possible to select transparency for both colors. The former "Original Image" background can be achieved by setting the background alpha to zero, and the former "Transparent" background can be achieved by starting with a new, transparent image layer, and also setting the background alpha to zero. The tool background color can be used by copy-paste (right-click on any color selector to access the color copy-paste)

You can build your own Pixelitor form the new sources or wait for the next release, which should happen in 1-2 weeks.

**Comment by lbalazscs** [comment]
The implementation is included in the final 4.3.0, which was just released.
