### ISSUE TITLE
Copy image data to clipboard while the filter is open.

### ISSUE THREAD

**Issue by LinuxBeaver** [lbalazscs/Pixelitor#165]
![image](https://user-images.githubusercontent.com/78667207/111729882-0104cc00-8868-11eb-8a05-e89b1539824c.png)
A "copy active image to clipboard" button would be a great enhancement

I know it is impossible (without an advance form of non-destructive editing) to edit content while a filter dialog is open. However,  I would like to know if it would be possible to copy an active filter preview to the clipboard. Instead of commiting an edit, I can just copy multiple edits to my clipboard manager and select my a favorite.

**Comment by lbalazscs** [comment]
In the newest GitHub source the Ctrl-Shift-C keyboard shortcut also works when a filter dialog is active. It copies the image that is currently visible.

**Comment by Just-Another-Gnumer** [comment]
Thanks, 4.24 is definitely going to be an excited release with these new features.

**Comment by Just-Another-Gnumer** [comment]
Also it would be awesome if Ctrl C could copy just the active layer so Pixelitor could work easily with Gimp on certain things.  Pix 4.2.4 could be out less then a week right?

**Comment by lbalazscs** [comment]
I wanted to also add Ctrl-C, but then I realized that it's not so easy, because the way it is implemented now, it would copy the original layer image and not the filter preview. But this is also planned.

4.2.4-beta3 should be out in a few days. There are some bugs that I want to solve before releasing 4.2.4, and I don't know how long will it take. But anyway, if you are not affected, you can treat these builds as 4.2.4, they aren't unstable.

**Comment by Just-Another-Gnumer** [comment]
I have not noticed any bugs outside of stroke effects in certain filters like LissaJous Curve, Flower of Life, Spider Web and the other ones with lines.

**Comment by lbalazscs** [comment]
The biggest problem is that I recently discovered that not all tool buttons fit on some small laptop screens. I'll probably have to decrease the tool button size.

What kind of errors/warnings do you get withe the "render shape" filters? I know that they can get sometimes slow, but the only warning you should get is that some settings in Stroke Settings/Stroke Type/Line Type have "can be slow" in their name. (I know that sometimes those filters are slow even without using these line types). If you get other errors/warnings in a way that can be reproduced, please open a new issue.

**Comment by lbalazscs** [comment]
Both Ctrl-C and Ctrl-Shift-C should work in the 4.2.4 beta 3, see https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta3

**Comment by lbalazscs** [comment]
The implementation is included in the final 4.3.0, which was just released.
