### ISSUE TITLE
saved file can be opened any number of times

### ISSUE THREAD

**Issue by r3b3kka** [lbalazscs/Pixelitor#167]
Summary: saved file can be opened any number of times
	Severity: minor
	Priority: medium
	Environment: Windows 10, Java Environment 1.8.0, Pixelitor 4.2.3
	Steps to reproduced: 
	1) open saved file
	2) reopen this file
	Result: this file opens twice or more
 
![image](https://user-images.githubusercontent.com/81333767/112394975-242fef80-8d30-11eb-9051-4e285e55e929.png)

Expected result: a warning about an open this file should open

**Comment by lbalazscs** [comment]
It the GitHub version there is a warning now.
![openedwarning](https://user-images.githubusercontent.com/9939454/112566961-39fced80-8de0-11eb-9c20-27137b5dfaeb.png)

**Comment by lbalazscs** [comment]
The warning is included in the final 4.3.0, which was just released.
