### ISSUE TITLE
pasting copied selection does not work on any layers

### ISSUE THREAD

**Issue by r3b3kka** [lbalazscs/Pixelitor#168]
Summary: pasting copied selection does not work on any layers
	Severity: Major
	Priority: High
	Environment: Windows 10, Java Environment 1.8.0, Pixelitor 4.2.3
	Steps to reproduced:
	1) select region on picture
	2) copy selection
	3) create new layer
	4) past selection
	Result:
![image](https://user-images.githubusercontent.com/81333767/112395070-4fb2da00-8d30-11eb-97e2-f6e2fd30f65c.png)

	Expected result: the copied image area is pasted onto the layer

**Comment by lbalazscs** [comment]
I'm not sure I understand this.
There are two kinds of paste in Pixelitor: paste as new image (Ctrl-V) and paste as new layer (Ctrl-Shift-V). There is no paste into current layer. 

If you want the result of paste to be in the current layer, you can paste as new layer, and then use "merge down" on another layer.
