### ISSUE TITLE
Wat

### ISSUE THREAD

**Issue by linxon** [lbalazscs/Pixelitor#17]
![selection_025](https://user-images.githubusercontent.com/8144644/46488210-b3688600-c80a-11e8-9955-e9f267ceadbc.png)
![untitled](https://user-images.githubusercontent.com/8144644/46488193-ab104b00-c80a-11e8-9a09-0ed9f060b5da.jpg)

**Comment by lbalazscs** [comment]
Oh, that photo scared me, but I deserved it :) Fixed.
