### ISSUE TITLE
 when the file resolution is higher than 2000 px on both sides, the brush draws with straight lines

### ISSUE THREAD

**Issue by r3b3kka** [lbalazscs/Pixelitor#171]
Summary: when the file resolution is higher than 2000 px on both sides, the brush draws with straight lines
	Severity: major
	Priority: high
	Environment: Windows 10, Java Environment 1.8.0, Pixelitor 4.2.3
	Steps to reproduced:
	1) create new file with resolution higher than 2000 px on both sides
	2) paint with a brush
	Result:
	 
![image](https://user-images.githubusercontent.com/81333767/112395322-be903300-8d30-11eb-8f99-521ab4d3a822.png)

	Expected result: lines should be smooth

**Comment by lbalazscs** [comment]
This is a performance problem with large images. In 4.2.4-beta2 the performance is much better if there is only one layer. It's still bad, if there are more than one layers.

4.2.4-beta2 can be downloaded here: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta2

**Comment by lbalazscs** [comment]
The improvement is included in the final 4.3.0, which was just released.
