### ISSUE TITLE
at high file resolution, the picture does not fit completely

### ISSUE THREAD

**Issue by r3b3kka** [lbalazscs/Pixelitor#172]
Summary: at high file resolution, the picture does not fit completely
	Severity: minor
	Priority: low
	Environment: Windows 10, Java Environment 1.8.0, Pixelitor 4.2.3
	Steps to reproduced:
	1) open or create file with high resolution (regarding monitor resolution. At monitor resolution 1920x1080px, picture resolution should be more 8000x8000px in fullscreen mode)
	Result:
	 
![image](https://user-images.githubusercontent.com/81333767/112395396-dc5d9800-8d30-11eb-9ccb-de0cc353cbc3.png)

	Expected result: the picture completely fits into the workspace

**Comment by lbalazscs** [comment]
The fix just made it into the 4.2.4 beta 3 release: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta3

**Comment by lbalazscs** [comment]
The fix is included in the final 4.3.0, which was just released.
