### ISSUE TITLE
UI buttons are cut off when clicking on the button "Randomize Settings" in the function "Four color gradient"

### ISSUE THREAD

**Issue by Elissa19** [lbalazscs/Pixelitor#174]
Summary: UI buttons are cut off when clicking on the button "Randomize Settings" in the function "Four color gradient" 
Severity: low
Priority: low
Environment: Windows 7, Java Environment 1.8.0, Pixelitor 4.2.3
Steps to reproduced:
1) create new image
2) select "Color -> Fill with... -> Four color gradient"
3) click on "Randomize Settings"
Result:
![bug1](https://user-images.githubusercontent.com/73542841/112424064-54928080-8d66-11eb-832a-de8f6ba41e8c.PNG)

**Comment by lbalazscs** [comment]
This was indeed a bug in version 4.2.3, but it's already fixed in 4.2.4-beta3, which can be downloaded at https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta3

**Comment by lbalazscs** [comment]
The fix is included in the final 4.3.0, which was just released.
