### ISSUE TITLE
Doesn't work scrolling with the mouse wheel after Zoom In

### ISSUE THREAD

**Issue by Elissa19** [lbalazscs/Pixelitor#175]
Summary: Doesn't work scrolling with the mouse wheel after Zoom In 
Severity: low
Priority: low
Environment: Windows 7, Java Environment 1.8.0, Pixelitor 4.2.3
Steps to reproduced:
1) create/open image
2) Zoom In to 141.4%
3) turn the mouse wheel 
Result: the slider doesn't move
![bug3](https://user-images.githubusercontent.com/73542841/112458425-591f5f00-8d8f-11eb-8d20-d6c1f3ba5597.PNG)

**Comment by lbalazscs** [comment]
In version 4.2.3 you have to hold down the Ctrl key while zooming to zoom in using the scroll wheel. In version 4.2.4-beta3 this is configurable in Preferences, and by default the scroll wheel can be used without ctrl.

Version 4.2.4-beta3 can be downloaded from here: https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta3

Also note that in both versions the mouse has to be in the canvas area while scrolling.
