### ISSUE TITLE
Locked functions "Dot relative size" and "Fill Fuzzines" in the tool "Pointillize"

### ISSUE THREAD

**Issue by Elissa19** [lbalazscs/Pixelitor#176]
Summary: Functions "Dot Relative Size" and "Fill Fuzzines" in the tool "Pointillize" are locked, but change after pressing the "Randomize Settings" button
Severity: medium
Priority: medium
1) create new image
2) select "Filter -> Artistic -> Poitillize"
3) click on "Randomize Settings"
Result: locked fields are changed
![bug2-1](https://user-images.githubusercontent.com/73542841/112459109-0db98080-8d90-11eb-8f9d-6b308c4b0493.PNG)
![bug2-2](https://user-images.githubusercontent.com/73542841/112459124-10b47100-8d90-11eb-8a74-b4bf3281c3e5.PNG)

**Comment by lbalazscs** [comment]
The greyed out options are ignored even if they change, but I realize that this can be confusing, so I plan to fix it.

**Comment by lbalazscs** [comment]
The fix is included in the final 4.3.0, which was just released.
