### ISSUE TITLE
The empty "Recent documents' menu looks like a menu with a nested list

### ISSUE THREAD

**Issue by a79219505050** [lbalazscs/Pixelitor#182]
Preconditional: 
The recent files menu is empty

Steps to reproduce:
1.Open the menu file / recent files

Expected result: there is no arrow to the right of the menu name to indicate that there is a nested list
Actual result: there is an arrow to the right of the menu item to go to a nested list, nothing happens when the menu item is selected

<img width="184" alt="2" src="https://user-images.githubusercontent.com/82383267/114751693-21884f00-9d5e-11eb-871d-99940ea58e92.png">

**Comment by lbalazscs** [comment]
Fixed in GitHub (the recent menu is never empty now, because the "Clear Recent Files" menu is always there, even if there are no recent files)

**Comment by lbalazscs** [comment]
The fix is included in the final 4.3.0, which was just released.
