### ISSUE TITLE
Missing brush outline when using the " Brush Tool"

### ISSUE THREAD

**Issue by Azirafel17** [lbalazscs/Pixelitor#23]
Reproducibility: Always
Severity: Major
Priority: Medium
Software:
	Pixelitor 4.2.0
	Windows 10 64 Bit
	Java Version 1.8.0_221
Description:
When you use the Brush element, there is no outline around the element in the work area

Steps to reproduce:
1. On the toolbar, select brush tool 
2. Move the cursor to workspace 
3. There is no outline of the brush tool on the workspace
![Screenshot_1](https://user-images.githubusercontent.com/54812116/64177487-cb68df80-ce89-11e9-832c-92efb955c576.jpg)

**Comment by lbalazscs** [comment]
Implemented in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
Implemented in Pixelitor version 4.2.3, released today.
