### ISSUE TITLE
Incorrect operation of the "Clone Stamp tool" after changing the brush radius

### ISSUE THREAD

**Issue by Azirafel17** [lbalazscs/Pixelitor#24]
Reproducibility: Always
Severity: Major
Priority: Medium
Software:
	Pixelitor 4.2.0
	Windows 10 64 Bit
	Java Version 1.8.0_221
Description:
After changing the brush radius while using the clone stamp tool, the cloning center is shifted

Steps to reproduce:
1. Create a new picture with an arbitrary size and color background. For example: size-500px *500 px, background color-white
2. Select the "brush tool". Select the settings "brush tool". Example: Radius-75, Brush-Hard
3. Draw a circle anywhere in the workspace. For example: bottom left
4. On the toolbar, select "Clone Stamp tool". Select the settings "Clone Stamp tool". Example: Radius-20, Brush-Hard
5. Hold down " Alt " and press the cursor on the center of the black circle
6. Draw a circle using the “clone stamp tool” in the upper right of the work area
7. Change brush radius to 50
8. Draw a circle in the same place using the "clone stamp tool"
9. There was an offset image

the result of a bug in the screenshot:
![Screenshot_3](https://user-images.githubusercontent.com/54812116/64181539-d6733e00-ce90-11e9-91c2-b206443b444b.jpg)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
