### ISSUE TITLE
Can there be donations?

### ISSUE THREAD

**Issue by jointri** [lbalazscs/Pixelitor#253]
The fact that you can do stuff that isn't possible in GIMP such as non destructive editing or smart objects and GIMP won't have for probably a matter of years makes this program a godsend. You really should be paid for your hard work, can you consider allowing donations so you can be rewarded for your hard work?

**Comment by LinuxBeaver** [comment]
hey, I see your profile picture is Jenny. I am a fan of MLAATR!
![image](https://user-images.githubusercontent.com/78667207/167921380-c0bec380-1879-46f6-b486-27be867d742e.png)


Gimp's reason for not having NDE purely has to do with Gimp's limitations and not the powerful GEGL engine that Gimp uses. GEGL already has non-destructive node based editing that is orders of magnitude ahead of Pixelitor but Gimp just fails to tap into it.

**Comment by lbalazscs** [comment]
Thank you, but I think Pixelitor is not popular enough at the moment to be worth asking for donations. It's not something that I think about. You can help more by reporting bugs, coming up with good ideas, or (best of all) contributing code...
