### ISSUE TITLE
Program error when activate the "Pixel Grid" without opening image.

### ISSUE THREAD

**Issue by krivitsky-anton** [lbalazscs/Pixelitor#26]
Severity: Minor.
Frequency: Always.
Priority: Low.
Environment: Windows 7 x64, Java 1.8.0_221, Pixelitor 4.2.0.
Action performed:
1. Run the Pixelitor.
2. Click on "View" and choose the "Show Pixel Grid".

Actual result: Program error message appeared.
Expected result: The field "Show Pixel Grid" is unavailable while image not opened. 

![Program error](https://user-images.githubusercontent.com/21159192/64201712-8197ed80-ceb9-11e9-9062-c67e0e4d4122.jpg)

**Comment by lbalazscs** [comment]
The fix is in GitHub, it will be in  the next version

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
