### ISSUE TITLE
Negative number of "Undo/Redo Levels".

### ISSUE THREAD

**Issue by krivitsky-anton** [lbalazscs/Pixelitor#27]
Severity: Minor.
Frequency: Always.
Priority: Low.
Environment: Windows 7 x64, Java 1.8.0_221, Pixelitor 4.2.0.
Action performed:
1. Run the Pixelitor.
2. Click on "Edit" and choose the "Preferences...".
3. Enter a negative number to "Undo/Redo Levels" field , for example -1.
4. Click "Close".

Actual result: There are no limits of the usage "Undo"/"Redo" buttons.
Expected result: There is validation on non-negative "Undo/Redo Levels" values.

![UndoRedo Levels](https://user-images.githubusercontent.com/21159192/64204013-0c2f1b80-cebf-11e9-8afd-4a47968941a1.jpg)

**Comment by lbalazscs** [comment]
Good catch! I never thought about negative values... 
The fix is in the GitHub repository, and it will be in the next release.
I also fixed similar problems in the "New Image" and "Auto Paint" dialogs.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
