### ISSUE TITLE
org.freedesktop.Platform 20.08 is no longer receiving fixes and security updates

### ISSUE THREAD

**Issue by LinuxOpa** [lbalazscs/Pixelitor#271]
Info: org.freedesktop.Platform//20.08 is end-of-life, with reason:
**org.freedesktop.Platform 20.08** is no longer receiving fixes and security updates. Please update to a supported runtime version.
Applications using this runtime:
   **io.sourceforge.Pixelitor**

**Comment by lbalazscs** [comment]
The recently released version 4.3.1 upgrades to  org.freedesktop.Platform/22.08.
