### ISSUE TITLE
Saving file with special characters < and > in "File Name" field.

### ISSUE THREAD

**Issue by krivitsky-anton** [lbalazscs/Pixelitor#28]
Severity: Minor.
Frequency: Always.
Priority: Low.
Environment: Windows 7 x64, Java 1.8.0_221, Pixelitor 4.2.0.
Action performed:

1. Run the Pixelitor.
2. Click on "File" and choose the "New Image...".
3. Click "Ok".
4. Click on "File" and choose the "Save As...".
5. Enter text with special character '<' or '>' in "File Name" field, for example "test>".
6. Choose the type of the file, for example "JPEG files".
7. Choose the location to save the file.
8. Click "Save".

Actual result: An inscription appeared that the file was saved successfully, but it is not.
Expected result: Impossible to click "Save" button, if forbidden special characters are used in the "File Name" field.

![FileSave](https://user-images.githubusercontent.com/21159192/64207177-4f40bd00-cec6-11e9-9ba6-6ec23de8c1cf.jpg)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
