### ISSUE TITLE
[Feature request] Crop to content

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#281]
Now and then I find myself in a situation where all I need to to do with an image is trim extra padding - so only the graphical content is left. Usually these images have a lot of transparent area and a small piece of graphics in the middle, but sometimes they have a one-color background with a small piece of graphics. A function that simply cuts away either all transparent parts around the drawing, or all single-colored parts - leaving only a square image with the actual graphics - would be really useful. Would it be possible to implement something like that? Tell me if you want a few examples to show how I mean.

**Comment by lbalazscs** [comment]
The newest commit implements this feature (it's in the menu Images/Crop to Content). 

It only removes transparent pixels (not uniform backgrounds), but you can turn your uniform backgrounds into transparent pixels by using the Paint Bucket Tool, setting the Tolerance slider to 0, and the "Fill with" to transparent.

It should be in the next release, which hopefully will be released soon. You can also build Pixelitor on your own, or you can get the jar file built by github, as explained at https://github.com/lbalazscs/Pixelitor/wiki/Downloading-the-latest-development-build

**Comment by Imerion** [comment]
Awesome! Thanks! I really appreciate that you are so helpful implementing new features when requested like this.
