### ISSUE TITLE
[Feature Request] Display color difference

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#289]
I might have mentioned this before, sorry if that is the case. One thing I have found useful, especially when working with web or UI design, is to see how large the contrast difference between two chosen colors are. I have seen such a function in a few other image editors and design tools, where it is possible to see the difference between colors in percent on a scale where pure white and black would show 100% difference and if the same color is chosen for both active colors it would show 0%. Usually this is displayed in proximity to the chosen colors or in the color choser dialog. How about implementing something like that in Pixelitor?

**Comment by lbalazscs** [comment]
I understand what you're looking for, and how it would be useful. However, I have to say that I'm not very excited to add this feature. There are actually a lot of different ways to measure the "difference" (or "contrast difference", which would not be the same) between two colors, and it's not always clear which one would be the most useful for a particular user. 

But, the good news is that even without this feature, it's still easy to copy and paste colors from other tools into Pixelitor or vice versa. You can simply copy a color as a HTML hex string from any tool to the clipboard, and then you can right-click on any color picker in Pixelitor and select "Paste Color". 

For example Pixelitor can be used with this page: https://coolors.co/contrast-checker

**Comment by Imerion** [comment]
I understand the problem, and you should of course not implement something unless it feels right to do. I have actually been using a page just like that, so I can keep doing that. Thanks again for a quick answer!
