### ISSUE TITLE
Application’s tools stop working after opening system menu

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#29]
**Description:** if, while working in the application, a combination of keys ‘Alt+Space’ is pressed (opening the application’s system menu), then all of the following tools stop working: Move Tool, Crop Tool, Selection Tool, Brush Tool, Clone Stamp Tool, Eraser Tool, Smudge Tool, Gradient Tool, Paint Bucket Tool, Color Picker Tool, Pen Tool, Shapes Tool, Hand Tool and Zoom Tool.
**Actual result:** after closing the system menu, the tools stop working.
**Expected result:** after closing the system menu, the tools work correctly.

**Steps to reproduce:**
1.	Create or open a file.
2.	Press Alt+Space to open the system menu and close it.
3.	Select a tool and use it (e.g. by pressing left mouse button and dragging the cursor across the screen).
**Defect:** any chosen tool is not working unless the application is restarted.

**Reproducibility:** Always

**Severity:** Major

**Priority:** Normal

**Symptom:** System crash

**Workaround:** None

**Comments:** System menu, opened via clicking the left mouse button in the top-left corner of the application window, does not stop the tools from working. 
Tested on: Windows 10 Pro 64-bit, Pixelitor 4.2.0, Java Version 8 update 221.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
