### ISSUE TITLE
[Feature Request] Make seamless tile

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#290]
Another thing I might have mentioned before - sorry if that is the case!

I often use Pixelitor to create textures for games, UI backgrounds, web pages, etc. Usually they are supposed to be tiled and fit together, for example using a 64x64px block repeatedly over a larger surface. GIMP has a filter called "Make seamless tile" that takes any image and harmonizes the sides, so it can instantly be repeated in that way. This can often save quite a bit of time otherwise spent on cutting, pasting and in other ways making sure an image can be tiled. I have no idea how hard such a function would be to implement, but if it is not hard it would be really nice to see it in Pixelitor.

**Comment by lbalazscs** [comment]
Seamless texture generation is definitely something that would be awesome to have, but it's not exactly a walk in the park to implement, so it may not be something we see in Pixelitor anytime soon...

In the meantime, you can still use Pixelitor in parallel with Gimp to get the job done by copy-pasting images between them. Another option you could try is using the multilayer OpenRaster image format, which can be opened and saved by both Pixelitor and GIMP.

Also, you may want to check out some of the new AI-based texture generation tools. For example: https://replicate.com/tommoore515/material_stable_diffusion

**Comment by Imerion** [comment]
I understand this might be complicated either way, but I don't think what I'm looking for is that advanced. It doesn't have to create seamless textures on the fly, but rather apply an effect that sort of "forces" the seamlessness. Here is an example with a texture I quickly generated in Pixelitor and then the same image with the filter applied:

![Texture1](https://user-images.githubusercontent.com/16926509/215322684-da08e894-7a24-490a-b0b1-fbb5bdf074be.png)

![Texture2](https://user-images.githubusercontent.com/16926509/215322692-274818bf-9cc1-4898-8995-b99549ecc862.png)

**Comment by lbalazscs** [comment]
Oh, you mean this? https://docs.gimp.org/2.10/en/gimp-filter-tile-seamless.html
This indeed doesn't seem to be hard, and I might do it.

**Comment by Imerion** [comment]
Yes, that's it! Thanks!

**Comment by lbalazscs** [comment]
The newest commit contains the new filter. It's under Filter/Displace, because it's kind of similar to the Offset filter. It works just like the Gimp filter, except it has an extra "Center" option. The default position of the Center corresponds to the Gimp settings, but you can move it to protect a particular part of the image from overlapping. For relatively homogenous images it's not very useful, and it's probably best to leave it at the default.

**Comment by Imerion** [comment]
That is fantastic! And a smart and useful addition too! I really wish I could support you more in some way, all your work is really appreciated. At least I try to spread the word about Pixelitor when I get the chance. :)
