### ISSUE TITLE
[Bug] Program error when canceling after selecting Add linked (Smart object)

### ISSUE THREAD

**Issue by Imerion** [lbalazscs/Pixelitor#294]
When testing the various new experimental features I found a bug related to the Smart Objects: when choosing "Add linked" under "Smart Object" and then pressing "Cancel" instead of choosing a file I encounter a program error. Here is the stack trace I receive:

`
Program Error

Message:
    java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because "file" is null
Level:
    SEVERE
Stack Trace:
Cannot invoke "java.io.File.getName()" because "file" is null
    pixelitor.io.FileFormat.fromFile(FileFormat.java:148)
    pixelitor.io.IO.loadCompAsync(IO.java:75)
    pixelitor.menus.MenuBar.lambda$createSmartObjectSubmenu$15(MenuBar.java:540)
    pixelitor.gui.utils.OpenViewEnabledAction.actionPerformed(OpenViewEnabledAction.java:71)
    java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
    java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
    java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
    java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
    java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
    java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
    java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
    java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
    java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
    java.desktop/java.awt.Component.processEvent(Component.java:6391)
    java.desktop/java.awt.Container.processEvent(Container.java:2266)
    java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
    java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
    java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
    java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
    java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
    java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
    java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
    java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
    java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
    java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
    java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
    java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
    java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by lbalazscs** [comment]
Great job on finding bugs! This one should be fixed in the latest GitHub version. 

I also added a few sentences about smart object linking and cloning at https://pixelitor.sourceforge.io/documentation.html

BTW, if you notice anything important that is unclear or missing in the documentation, please don't hesitate to open a documentation bug. Your feedback is always welcome and appreciated.

**Comment by Imerion** [comment]
Nice!

And that is a good suggestion, I will take a look through the documentation as well.
