### ISSUE TITLE
No error message when rewriting a file with the ‘read-only’ attribute

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#30]
**Description:** When trying to replace a file with the ‘read-only’ attribute with its modified version, the application does not show an error message stating that it is impossible to modify the initial file. Instead, it states that the changes were saved successfully. If the modified file is closed and opened again, all changes are lost.
**Actual result:** the application does not show an error message saying that it is impossible to modify the file with the ‘read-only’ attribute and displays a message ‘<File name> was saved’ in the status bar at the bottom of the window.
**Expected result:** the application shows a message stating that the chosen file is read-only and proposes to save the file under another name.

**Steps to reproduce:**
1.	Prepare and open a graphic file with the ‘read-only’ attribute.
2.	Modify it using any tool (e.g. using the Brush Tool and doing several strokes across the picture) and select ‘File’ -> ‘Save As…’.
3.	Find the initial graphic file on the disk and choose to overwrite it.
**Defect:** the application closes the ‘Save As’ window and show a message ‘<File name> was saved.’ in the status bar at the bottom of the window.

**Reproducibility:** Always

**Severity:** Medium

**Priority:** Normal

**Symptom:** Data corruption/loss

**Workaround:** None

**Comments:** This bug might pose a serious threat due to the fact that a user might unknowingly spend a lot of time modifying a read-only file and lose all progress after overwriting the initial file. If a modified file is saved under another name, everything works as intended.
Tested on: Windows 10 Pro 64-bit, Pixelitor 4.2.0, Java Version 8 update 221.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
