### ISSUE TITLE
Tool hotkeys do not work with Cyrillic keyboard layout

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#31]
**Description:** When working with the application, tool hotkeys do not work if a Cyrillic keyboard layout is turned on. 
**Actual result:** tool hotkeys do not work with Cyrillic keyboard layout on.
**Expected result:** tool hotkeys properly work with Cyrillic keyboard layout on.

**Steps to reproduce:**

1.	Install, if needed, a Cyrillic (e.g. Russian) keyboard layout.
2.	Create a new file in the application.
3.	Switch to the Cyrillic keyboard.
4.	Press a hotkey for a tool (e.g. E for Eraser Tool or P for Pen Tool).
**Defect:** a corresponding tool does not become active if Cyrillic keyboard layout is on.

**Reproducibility:** Always

**Severity:** Medium

**Priority:** Normal

**Symptom:** Unexpected behaviour

**Workaround:** Switching back to any Western keyboard layout solves the issue.

**Comments:** Keyboard shortcuts, such as ‘Save As…’ (Ctrl+Shift+S), ‘Copy Layer’ (Ctrl+C), ‘Invert’ (Ctrl+I) etc., work properly with the Cyrillic keyboard, though.
The defect was tested on the Russian keyboard layout.
Tested on: Windows 10 Pro 64-bit, Pixelitor 4.2.0, Java Version 8 update 221.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
