### ISSUE TITLE
Port to C/C++

### ISSUE THREAD

**Issue by AmgadHasan** [lbalazscs/Pixelitor#312]
Hi.
Can this project be ported to C or C++?
This will make it easier to run on linux without using jvm

**Comment by lbalazscs** [comment]
Well, technically it's possible, but it would require a lot of work (essentially rewriting everything), and I'm not interested in that.

Note that the Flathub-based installer includes an OpenJDK. There might be .rpm and .deb installers in the future too. And theoretically, Java programs can be compiled ahead-of-time.

**Comment by AmgadHasan** [comment]
> Well, technically it's possible, but it would require a lot of work (essentially rewriting everything), and I'm not interested in that.

I didn't mean rewriting it from scratch in a new language. Isn't there a way to refactor systematically project from one language to another? I am not an expert at this so maybe someone else might help.
> Note that the Flathub-based installer includes an OpenJDK. There might be .rpm and .deb installers in the future too. And theoretically, Java programs can be compiled ahead-of-time.

So can it be compiled ahead of time and released as an executable file that can be run without jvm?
