### ISSUE TITLE
Unexpected resizing of a drawn shape using the Shapes Tool

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#32]
**Description:** When using ‘Drag from the center’ (hold Alt with Left mouse button) and ‘Move the shape’ (hold Space with Left mouse button) features of the Shapes Tool in combination, an unexpected resizing of the desired shape was encountered. When the shape is configured and placed as desired, and the buttons are released, it shrinks as if the Alt button was not pressed.
**Actual result:** the desired shape shrinks while staying in place it was moved to.
**Expected result:** the desired shape retains its configuration and position.

**Steps to reproduce:**

1.	Create or open a file.
2.	Select the Shapes Tool.
3.	Press and hold Alt, then press and hold Left mouse button and drag the mouse to determine the configuration of a shape.
4.	While holding Alt+Left mouse button, press and hold Space to move the shape around.
5.	Release Alt and Space to leave the shape in the desired location.
6.	Without moving the mouse, release Left mouse button.
**Defect:** the shape shrinks while staying in place it was moved to.

**Reproducibility:** Always

**Severity:** Medium

**Priority:** Normal

**Symptom:** Unexpected behaviour

**Workaround:** None

**Comments:** Releasing all the buttons (Alt, Space and Left mouse button) at the same time might lead to opening of the application’s system menu with consequent crash described in the issue #29.
Tested on: Windows 10 Pro 64-bit, Pixelitor 4.2.0, Java Version 8 update 221.

**Attachments:**
Holding Alt+Space+Left mouse button 
![P_004_1](https://user-images.githubusercontent.com/54802328/64228110-03b30100-cf10-11e9-8e31-8d2ebd98acfa.png)
After releasing the buttons
![P_004_2](https://user-images.githubusercontent.com/54802328/64228120-0e6d9600-cf10-11e9-8351-6f7b6cd2eb1d.png)

**Comment by lbalazscs** [comment]
Fixed in GitHub (also a somewhat similar issue with the Selection Tool), it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
