### ISSUE TITLE
Brush tool replaces foreground colour on Alt+Left or Right mouse button click

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#33]
**Description:** While using the Brush Tool, an Alt+Left mouse button click or Alt+Right mouse button click anywhere in the current working area replaces the foreground colour of the brush with the colour that was under the cursor.
**Actual result:** the foreground color is replaced with the colour that was under the cursor when Alt+Left/Right mouse button was pressed (if the cursor was in the working area).
**Expected result:** nothing happens when on Alt+Left or Right mouse button click.

**Steps to reproduce:**

1.	Open a new file with a white background.
2.	Select the Brush Tool.
3.	Press D to Reset default colours (Foreground: Black, Background: White).
4.	Alt+Left mouse button click on the white background in the working area.
5.	Check that the foreground colour square in the bottom left has become white.
6.	Use Paint Bucket Tool and select any non-black and non-white colour, fill the working area.
7.	Press D to Reset default colours (Foreground: Black, Background: White).
8.	Select the Brush Tool.
9.	Alt+Right mouse button click in the working area.
10.	Check that the foreground colour square in the bottom left has become the same colour as the colour used to fill the area.
**Defect:** the foreground colour is replaced with the colour that was under the cursor in the moment of the Alt+Left/Right mouse button click.

**Reproducibility:** Always

**Severity:** Minor

**Priority:** Normal

**Symptom:** Unexpected behaviour

**Workaround:** None

**Comments:** Was not sure if this is a bug, but as it is not stated in the status bar tooltip of the Brush Tool and it defies the whole purpose of the Color Picker Tool, it was decided to report it as a bug.
Tested on: Windows 10 Pro 64-bit, Pixelitor 4.2.0, Java Version 8 update 221.

**Attachments:**
The feature is not stated in the tooltip in the status bar
![P_005](https://user-images.githubusercontent.com/54802328/64228413-f2b6bf80-cf10-11e9-889a-40380c1e4f8f.PNG)

**Comment by lbalazscs** [comment]
This is a feature, not a bug :) It is not described in the status bar tooltip (there is not enough space), but it is described in the "Help/Tip of the Day". The idea is that the user should be able to temporarily use the Color Picker Tool functionality without switching to the Color Picker Tool, thus saving some time. The space key is also special: in many tools holding down the space key temporarily transforms the current tool into Hand Tool.

**Comment by RehnerJD** [comment]
Dear Laszlo,

Thanks for the tip. Didn't know about this.

Cheers.
