### ISSUE TITLE
No tooltip for erasing pixels along the line for Eraser Tool

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#34]
**Description:** There is no tooltip in the status bar stating that it is possible to erase everything between two points with the Eraser Tool using Shift+Click
**Actual result:** When selecting the Eraser Tool, no tooltip stating that it is possible to erase along the line with a Shift+Click is shown in the status bar.
**Expected result:** When selecting the Eraser Tool, a tooltip stating that it is possible to erase along the line with a Shift+Click is shown in the status bar.

**Steps to reproduce:**

1.	Open the application.
2.	If the status bar is hidden, select ‘View’ -> ‘Show Status Bar’.
3.	Select Eraser Tool.
**Defect:** The tooltip in the status bar contains only the words ‘Eraser Tool: **click and drag** to erase pixels.’

**Reproducibility:** Always

**Severity:** Medium

**Priority:** Normal

**Symptom:** Unfriendly behaviour

**Workaround:** None

**Comments:** ‘Medium’ severity was selected because the feature might be useful to a user, but there is no way to learn about it unless they discover it empirically, which worsens user experience.
Tested on: Windows 10 Pro 64-bit, Pixelitor 4.2.0, Java Version 8 update 221.

**Attachments:**
The tooltip for the Eraser Tool
![P_006_1](https://user-images.githubusercontent.com/54802328/64228690-bd5ea180-cf11-11e9-8d7b-3cabdb4ef486.PNG)
Results of using the feature on a white background
![P_006_2](https://user-images.githubusercontent.com/54802328/64228698-c94a6380-cf11-11e9-8285-e8c098e64521.PNG)

**Comment by lbalazscs** [comment]
Fixed in GitHub, also for the similar issue with the clone tool. The fix will be released in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
