### ISSUE TITLE
Fields in the palette use default system language

### ISSUE THREAD

**Issue by RehnerJD** [lbalazscs/Pixelitor#35]
**Description:** Clicking on the foreground colour at the bottom of the toolbar opens a menu called ‘Set Foreground Color’ where the names of the fields responsible for Hue, Saturation, Brightness, Red, Green and Blue use system display language for their names.
**Actual result:** ‘Тон’, ‘Насыщенность’, ‘Яркость’, ‘Красный’, ‘Зелёный’ and ‘Синий’ (Russian words).
**Expected result:** ‘Hue’, ‘Sat’, ‘Bri’, ‘Red’, ‘Green’ and ‘Blue’ as in all other menus of the application.

**Steps to reproduce:**

1.	Set system display language to non-English language and follow the instructions for the changes to come into effect.
2.	In the application, click on the Foreground color icon in the bottom left of the screen.
3.	Check the names of the fields.
**Defect:** the field names responsible for Hue, Saturation, Brightness, Red, Green and Blue use system display language.

**Reproducibility:** Always

**Severity:** Minor

**Priority:** Normal

**Symptom:** Cosmetic flaw

**Workaround:** Set system display language to English.

**Comments:** Affects only said menu, other menus and hints are still in English.
Tested on: Windows 10 Pro 64-bit with Russian and English display language, Pixelitor 4.2.0, Java Version 8 update 221.

**Attachments:**
The menu with Russian system display language
![P_007_1](https://user-images.githubusercontent.com/54802328/64229050-e2074900-cf12-11e9-9045-766ee8b4e7e1.png)
The menu with English system display language
![P_007_2](https://user-images.githubusercontent.com/54802328/64229067-efbcce80-cf12-11e9-911e-75e297f69e0a.png)

**Comment by lbalazscs** [comment]
Fixed in GitGub, it will be in the next version

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
