### ISSUE TITLE
Layout elements does not shown when user press the Tab key

### ISSUE THREAD

**Issue by fisheye123** [lbalazscs/Pixelitor#41]
**Severity**: Minor
**Priority**: Low
**Reproducibility**: Always
**Environment**: Pixelitor 4.2.0, Windows 10 x64, Java 1.8.0_221
**Steps to reproduce**:
	1) Run the Pixelitor
	2) Press the Tab key 3-5 times
**Actual result**: Hidden layout elements not showing
**Expected result**: Hidden layout elements are shown

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
