### ISSUE TITLE
Arrange windows not working

### ISSUE THREAD

**Issue by Stasikanutyu** [lbalazscs/Pixelitor#43]
Description: An error is displayed when trying to arrange windows.
Expected Result: Several windows will merge into 1 side by side.

Playback Actions:

Open the application and open some photos.
click view and select any of the items in the arrange windows line.
Defect: Error is issued

Reproducibility: always

Severity: medium

Priority: Normal

Symptom: Unfriendly Behavior

Workaround: No

Comments: Checked: 64-bit version of Windows 10 Pro, Pixelitor 4.2.0, Java update version 8 221.

Attachments: 
![image](https://user-images.githubusercontent.com/54906132/64274905-98e4e280-cf6e-11e9-8e37-c01017b5f808.png)

**Comment by lbalazscs** [comment]
Cascade and Tile should work only when the images are in internal windows and not in tabs (see Edit/Preferences). But there was indeed a bug here, because these menus must be grayed out when the UI is tabs. Now they are grayed out (in the GitHub code, the fix will be in the next released version).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
