### ISSUE TITLE
Scaling error toolbar

### ISSUE THREAD

**Issue by ShirabK** [lbalazscs/Pixelitor#44]
When showing toolbar, the workspace moving up some distance from the program interface. If you open stats bar, part of the toolbar is hidden.
Link to screenshot: https://drive.google.com/drive/folders/1ey7RubBdt0aa9w3Gsugus9xzAsc33M53?usp=sharing

**Comment by ShirabK** [comment]
screen resolution 1366x768

**Comment by lbalazscs** [comment]
Thank you for reporting! I am closing this because is is a duplicate of issues #36 and #39 

BTW, you can attach an image directly to a GitHub issue: https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
