### ISSUE TITLE
UTF-8 encoding not supported when insert text

### ISSUE THREAD

**Issue by ShirabK** [lbalazscs/Pixelitor#46]
When inserting text in Cyrillic through Filter -> text, rectangles are displayed on the image
**Steps:**

1. Run the application and open the file
2. Open text insertion function Filter->Text
3. In the Text field, enter the word in Cyrillic

Result: The image shows rectangles (encoding error)
Expected Result: Cyrillic Text Displayed on Image

Screenshot:
![Screenshot_1](https://user-images.githubusercontent.com/54932787/64471169-fe57ef80-d177-11e9-92f2-2ec95df08e40.png)
Test environment: Windows 10 Home 64-bit, Pixelitor 4.2.0, Java Version 8.

**Comment by lbalazscs** [comment]
This is not a bug: it depends on the selected font type. If the selected font doesn't support a character then it cannot display it. I guess other apps also won't display Cyrillic Text when you select this font type. As you can see in my screenshot, there are no problems with Arial Black. You can search the web for "fonts with cyrillic support".

![Russian](https://user-images.githubusercontent.com/9939454/64472213-44eb2100-d15b-11e9-90f0-90fa67963cd5.png)
