### ISSUE TITLE
"Сtrl-Z" does not work correctly when undoing a mirror Brush Tool 

### ISSUE THREAD

**Issue by befanssolki** [lbalazscs/Pixelitor#47]
**Software**:
Pixelitor 4.2.0
Windows 10 x64
Java Version 1.8.0
Description: "Сtrl-Z" does not work correctly when undoing a mirror brush, 
If you make one click of the mirror brush, then ctrl-z will erase only one point

**Steps**:
1. Сhoose Brush Tool 
2. Сhoose a mirror (any)
3. Click on any area without moving the mouse

**Reproducibility**: Always

**Severity**: Medium

**Priority**: Normal

**Video**: https://drive.google.com/file/d/12I0aQIGxOW3_Q1fo9GhZlF0WkIIuvnLb/view?usp=sharing

**Comments**: The eraser also behaves.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
