### ISSUE TITLE
Incorrect work of "Paint Bucket Tool"

### ISSUE THREAD

**Issue by OmarovAmir** [lbalazscs/Pixelitor#53]
Reproducibility: Always
Severity: Major
Priority: High
Software:
Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_181

Description:
Paint Bucket Tool fills the area with black color and the rest of the empty area together. With other colors, which I used, everything is done correctly.

Steps to reproduce:
1. Create a new picture following example:
![Example](https://user-images.githubusercontent.com/55622089/65372218-5a9e3180-dc97-11e9-82b1-759c2842cb2b.jpg)
2. Select the "Paint Bucket Tool".
3. Press on the area with black color.
![Example1](https://user-images.githubusercontent.com/55622089/65372240-8d482a00-dc97-11e9-9e26-1f60f11e646c.jpg)
4. Press "CTRL + Z".
5. Press on the area with another color.
![Example2](https://user-images.githubusercontent.com/55622089/65372257-c1234f80-dc97-11e9-91c1-391b2cce9a59.jpg)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
