### ISSUE TITLE
Incorrect work of "Gradient Tool"

### ISSUE THREAD

**Issue by OmarovAmir** [lbalazscs/Pixelitor#54]
Reproducibility: Always
Severity: Major
Priority: High
Software:
Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_181

Description:
Gradient Tool fills the empty area in black color and after undone of creating of gradient in the window of layers on this layer background remains filled in black color and gradient effect.

Steps to reproduce:
1. Create a new picture following example:
![Bug2_1](https://user-images.githubusercontent.com/55622089/65372649-0dbd5980-dc9d-11e9-86b9-0fdda33c9625.jpg)
2. Select the "Gradient Tool".
3.Click and drag to draw gradient anywhere.
![Bug2_2](https://user-images.githubusercontent.com/55622089/65372688-5ffe7a80-dc9d-11e9-9b20-540102aa1c4f.jpg)
4. Press "CTRL+Z".
![Bug2_3](https://user-images.githubusercontent.com/55622089/65372815-072fe180-dc9f-11e9-9729-2f0b9101a299.jpg)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
