### ISSUE TITLE
"Circles" brush problem.

### ISSUE THREAD

**Issue by phelieros** [lbalazscs/Pixelitor#57]
Reproducibility: Always
Severity: Minor
Priority: Low
Software: Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_201

Description:
Undoing "circles" brush leaves traces behind. It might be related to "Radius depends on mouse speed" brush setting. With it disabled, undoing this brush works as intended.

Steps to reproduce:
1. Use "Circles" brush to draw something on the canvas.
2. Press ctrl+z to undo it. Undoing leaves traces of the brush behind.
3. Disable "Radius depends on mouse speed" setting.
4. Draw on canvas. Undoing works as intended.

Video:
[YHEVWdBips.zip](https://github.com/lbalazscs/Pixelitor/files/3655849/YHEVWdBips.zip)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
