### ISSUE TITLE
"Connect" brush problem.

### ISSUE THREAD

**Issue by phelieros** [lbalazscs/Pixelitor#58]
Reproducibility: Always
Severity: Minor
Priority: Low
Software: Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_201

Description:
Undoing "Connect" brush doesn't work as intended. Lines get thicker each time you undo.

Steps to reproduce:
1. Use "Connect" brush to draw something on the canvas.
2. Press ctrl+z to undo it.
3. Repeat steps 1 and 2 several times. Each time drawn line will get thicker.
4. Open new image and draw with "Connect" brush in it. 
5. Switch back to original image. Brush will create thin lines as expected.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.3, released today.
