### ISSUE TITLE
Reload and Undo issue

### ISSUE THREAD

**Issue by phelieros** [lbalazscs/Pixelitor#59]
Reproducibility: Always
Severity: Minor
Priority: Low
Software: Pixelitor 4.2.0
Windows 7 Professional 64 Bit
Java Version 1.8.0_201

Description:
Parts of old image show up when drawing on canvas after working with brushes, then reloading image and undoing reload. 

Steps to reproduce:
1. Use brush to draw something on the canvas.
2. Reload image.
3. Press ctrl+z to undo reload. Image will still look like it was originally.
4. Draw something with brush of different color. You will see parts of old image.

Video:
[oFwvWLaWvi.zip](https://github.com/lbalazscs/Pixelitor/files/3655861/oFwvWLaWvi.zip)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.1, released today.
