### ISSUE TITLE
Rotation angle on the slider is not reset

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#61]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S4 Minor
**Priority:** P3 Low
**Component:** FUNCTIONAL

**Summary:**
Rotation angle on the slider (in the Text adding and editing interface) is not reset when pressing the Reset button when the value in the cell is 360 (important: the value was entered with the mouse by moving the slider).

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. In the Rotation field, use mouse to move slider to value 360.
5. Try to reset the value by clicking on the Reset button on the right.

**Expected result:**
The value of the rotation angle in the cell should be reset to 0.

**Link (screenshots/video):**
https://yadi.sk/i/yOJG2LGDg3nWGQ

**Additional Info:**
These 2 bugs are available on the same sliders in the next filter interfaces: [Motion Blur], [Swirl, Pinch, Bulge], [Underwater], [Glass Tiles], [Polar Glass Tiles -> Configure [Background]], [Polar Coordinates], [Wrap Around Arc], [Kaleidoscope], [Slice], [Cells], [Marble], [Wood], [Checker Pattern], [Starburst], [Emboss], [Random Spheres], [Smear], [Striped Halftone], [Transform Layer], [Color Wheel], [Text].

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
