### ISSUE TITLE
Rotation angle slider is reset to 0

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#62]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S4 Minor
**Priority:** P3 Low
**Component:** VISUAL

**Summary:**
Rotation angle slider (in the Text adding and editing interface) is reset to 0 when you manually specify a 360 value in cell (you can enter 360 manually and press Enter or increase the value to 360 by clicking on the ↑ button). However, the value in the cell remains unchanged, this is a visual bug.

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. In the Rotation field, manually enter 360 into the angle cell and press Enter, or increase the value to 360 by clicking on the ↑ button.
5. Watch the slider reset to 0 with the actual value of 360 in the cell.

**Expected result:**
The slider should remain at 360.

**Link (screenshots/video):**
https://yadi.sk/i/tSrjplLD47aT9g

**Additional Info:**
These 2 bugs are available on the same sliders in the next filter interfaces: [Motion Blur], [Swirl, Pinch, Bulge], [Underwater], [Glass Tiles], [Polar Glass Tiles -> Configure [Background]], [Polar Coordinates], [Wrap Around Arc], [Kaleidoscope], [Slice], [Cells], [Marble], [Wood], [Checker Pattern], [Starburst], [Emboss], [Random Spheres], [Smear], [Striped Halftone], [Transform Layer], [Color Wheel], [Text].

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
