### ISSUE TITLE
Bug in the Inner Glow effect for text

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#63]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S3 Major
**Priority:** P1 High
**Component:** FUNCTIONAL

**Summary:**
Bug in the Inner Glow effect for text. Inner glow goes out of the text frame, while these frame become visible on the image.

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. Add text and enable the Inner Glow effect.
5. Set the Opacity and Width to 100.

**Expected result:**
Inner glow should not goes out of the text frame.

**Link (screenshots/video):**
https://yadi.sk/i/OMOtYBuyFjS_Aw

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
