### ISSUE TITLE
Strikethrough, Underline, Kerning and Ligatures functions do not work for text effects

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#64]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S3 Major
**Priority:** P2 Medium
**Component:** FUNCTIONAL

**Summary:**
Strikethrough, Underline, Kerning and Ligatures functions do not work for text effects. This is very clearly seen in the Drop Shadow and Glow effects. For this reason, defects may appear in the text with the shadow/glow turned on, due to the kerning font and the shadow/glow out of sync, for which the kerning function does not work.

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. Add text and enable the effects of Glow, Inner Glow, Neon Border, Drop Shadow.
5. Open advanced text settings (Advanced...).
6. Add to text Strikethrough, Underline, Kerning, Ligatures.

**Expected result:**
Strikethrough, Underline, Kerning and Ligatures for text should work on text effects.

**Link (screenshots/video):**
https://yadi.sk/i/JCDOw9buCCCugw

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
