### ISSUE TITLE
In the Guides interfaces when scaling the window there are problems with the display of text

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#66]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S4 Minor
**Priority:** P3 Low
**Component:** UI

**Summary:**
In the interfaces [Add Horizontal Guide], [Add Vertical Guide], [Add Grid Guides] when scaling the window there are problems with the display of text. The text is superimposed on each other.

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding horizontal guide (View -> Add Horizontal Guide...).
4. Reduce window size.

**Expected result:**
Texts, sliders and other elements in interface should not be scaled when the window is reduced in size.

**Link (screenshots/video):**
https://yadi.sk/i/GqxOYNhS8r1xKg

**Comment by lbalazscs** [comment]
Please note that it is possible to insert screenshots  into github issues if you simply drag and drop the image file into the comment box, there is no need for external disk storage. (Just for the future, I already looked at these images)

https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
