### ISSUE TITLE
Direction of Motion Blur filter is inverted when filter quality changes

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#67]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S3 Major
**Priority:** P1 High
**Component:** FUNCTIONAL

**Summary:**
The direction of the Motion Blur filter is inverted when filter quality changes from Faster to High (and vice versa).

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Draw something to understand how the filter works.
4. Open the interface of the Motion Blur filter (Filter -> Blur/Sharpen -> Motion Blur...).
5. Set the Distance values to 200 and Direction to 135.
6. Change Quality from Faster to High (and vice versa).

**Expected result:**
The direction of the filter should not change when the quality changes.

**Link (screenshots/video):**
https://yadi.sk/i/FQJzbvnmJmO2Ng

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
