### ISSUE TITLE
Reset button in many interfaces is active by default

### ISSUE THREAD

**Issue by kr1zo** [lbalazscs/Pixelitor#68]
**Pixelitor version:** 4.2.1
**Java version:** 1.8.0_221
**OS:** Windows 10 x64

**Severity:** S4 Minor
**Priority:** P3 Low
**Component:** UI

**Summary:**
In many interfaces (not all), the Reset button for resetting the settings is active by default, but when you click on it, nothing happens and it remains active. But, if you change the value, the button will work and after will become inactive, as it should be. It is noticed that such buttons are in an unallocated field.

**Steps to reproduce:**
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding Marble filter (Filter -> Render -> Marble...).
4. In the Type and Wave Type fields, click on the active Reset button (without changing the initial value).

**Expected result:**
Reset button should be initially inactive if no changes have been made.

**Link (screenshots/video):**
https://yadi.sk/i/h1wvPINASiGNzw

**Additional Info:**
List of all the interfaces in which this bug is available:
Blur/Sharpen: [Focus], [Motion Blur], [Spin and Zoom Blur]
Distort (ALL): [Swirl, Pinch, Bulge], [Circle to Square], [Perspective], [Lens Over Image], [Magnify], [Turbulent Distortion], [Underwater], [Water Ripple], [Waves], [Angular Waves], [Radial Waves], [Glass Tiles], [Polar Glass Tiles], [Frosted Glass], [Little Planet], [Polar Coordinates], [Wrap Around Arc]
Dislocate: [Kaleidoscope], [Mirror], [Slice]
Light: [Flashlight]
Noise: [Add Noise], [Pixelate]
Render: [Plasma], [Cells], [Fractal Tree], [Marble], [Voronoi Diagram], [Starburst], [Grid], [Lissajous Curve], [Mystic Rose], [Spirograph]
Artistic: [Crystallize], [Oil Painting], [Pointillize], [Random Spheres], [Smear], [Stamp], [Weave], [Striped Halftone], [Concentric Halftone]
Find Edges: [Convolution Edge Detection]
Other: [Morphology], [2D Transitions], [Channel to Transparency]
Color Menu: [Color Balance], [Solarize], [Channel Invert], [Extract Channel], [Threshold], [Dither]

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
