### ISSUE TITLE
Rotation displaces text effects

### ISSUE THREAD

**Issue by Teeheej** [lbalazscs/Pixelitor#70]
**Pixelitor version**: 4.2.1
**Java version**: 1.8.0_222
**OS**: Windows 10 x64

**Reproducibility**: Always
**Severity**: S3 Major
**Priority**: P2 Medium
**Component**: Functional

**Summary**:
Applying rotation to the text frame moves text effects away. The bug affects Glow, Inner glow, Neon border and Drop shadow effects.

**Steps to reproduce**:
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. Add text and enable Glow effect.
5. Set the Opacity to 100 and Width to 30.
6. Set Rotation to 180 degrees.
**Expected result**: Rotated text has the Glow effect
**Actual result**: Glow effect is moved outside the text frame

The bug affects all 4 text effects. Slight rotation allows to track displacement of the effect.

**Comment by lbalazscs** [comment]
This is tricky because it depends on the Java version. The effects rotate OK with older versions and are bad with newer versions. Since everybody should use the newest version anyway, I intend to fix it.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
