### ISSUE TITLE
Opacity level of Brush Tool can be exceeded

### ISSUE THREAD

**Issue by Teeheej** [lbalazscs/Pixelitor#71]
**Pixelitor version**: 4.2.1
**Java version**: 1.8.0_222
**OS**: Windows 10 x64

**Reproducibility**: Always
**Severity**: S4 Minor
**Priority**: P3 Low
**Component**: Functional

**Summary**:
Pixelitor allows to set the Brush opacity to 9999999999 (10 symbols or more) what leads to a Program error.

**Steps to reproduce**:
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Choose Brush Tool on the tool panel.
4. Enter value “9999999999” in the “Opacity” field on the upper panel.
**Expected result 1**: Opacity is dropped to a maximum value of 100.
Or
**Expected result 2**: The warning on maximum opacity level is shown, user’s value from step 4 have not been set.
**Actual result**: A Program Error with message “_An exception occurred: For input string: "10000000000"_”. After closing the Error window opacity value is 9999999999. Attempt to use Brush Tool causes the same error.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
