### ISSUE TITLE
Incorrect work of the Text Effects applied to Segoe Script Font Type on certain Font sizes.

### ISSUE THREAD

**Issue by Teeheej** [lbalazscs/Pixelitor#72]
**Pixelitor version**: 4.2.1
**Java version**: 1.8.0_222
**OS**: Windows 10 x64

**Reproducibility**: Depends on availability of Segoe Script Font / Always
**Severity**: S4 Minor
**Priority**: P3 Low
**Component**: Functional

**Summary**:
Shape of the Text and shape of the Text Effect do not match when the Font Type is Segoe Script and the Font Size is more than 100. The bug affects only letters and all 4 Text effects: Glow, Inner Glow, Neon Border and Drop Shadow. Numbers and special symbols are not affected.

**Steps to reproduce**:
1. Run the Pixelitor.
2. Create a new image (Ctrl + N).
3. Open the interface for adding and editing text (Filter -> Text...).
4. Add text and set Font Type to Segoe Script. Text should consist of letters.
5. Set Font Size to 110.
6. Enable Glow Effect.
7. Set the Opacity to 100 and Width to 30.

**Expected result**: The shape of Glow effect matches the shape of Text.
**Actual result**: The shape of Glow effect is stretched to the right. Only the first symbol of the Text has proper Glow shape.

Screenshots: https://imgur.com/a/6KLKfzY

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version (in a few days).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
