### ISSUE TITLE
Inaccurate work of Batch Resize Tool in case of different source images

### ISSUE THREAD

**Issue by Teeheej** [lbalazscs/Pixelitor#74]
**Pixelitor version**: 4.2.1
**Java version**: 1.8.0_222
**OS**: Windows 10 x64

**Reproducibility**: Always
**Severity**: S3 Major
**Priority**: P3 Low
**Component**: Functional

**Summary**:
If source (processed) images are different in size, Batch Resize Tool excessively decreases resulting size of each next processed image. It occurs even in the case of enlargement.

**Steps to reproduce**:
1. Run the Pixelitor.
2. Initiate Batch Resize Tool (File -> Automate -> Batch Resize...)
3. In the field “Input Folder” choose a folder with ten 1280x720 px and 720x1280 px pictures sorted by name and placed alternately (“landscape” orientation – “portrait” orientation – “landscape” etc.). “Set_1_BatchResizeTest” folder may be used (see the link to test files below).
4. Set “Max Width” and “Max Height” values to 100. Output format – jpg.

**Expected result**: Output Folder contains ten resized pictures: 100x56 px and 56x100 px placed alternately when sorted by name.
**Actual result**: Program Error: “An exception occurred: Width (1) and height (0) cannot be <= 0”. Pixelitor opens pictures number 8 and 9. Output Folder does not contain pictures 8 and 9. The size of picture 7 is 2x1 px.

3 different tests on 3 sets of pictures have been conducted (9 tests in total):
**Test 1**: Batch Resize to a maximum Width and Height of 100.
**Test 2**: Batch Resize to a maximum Width of 640 and Height of 360 (proportional decrease)
**Test 3**: Batch Resize to a maximum Width of 2560 and Height of 1440 (proportional increase)

**Set 1**: Five 1280x720 px and Five 720x1280 px images sorted by name and placed alternately (1280x720 – 720x1280 – 1280x720 etc.), 10 in total.
**Set 2**: Five 1280x720 px and Five 720x1280 px images sorted by name and placed successively (all 1280x720 then all 720x1280)
**Set 3**: Ten identical pictures of 1280x720 px.

Only **Test 2** and **Test 3** on **Set 3** gave expected result.
**Test 3** on **Set 1** significantly decreased size of 8 images (out of 10) instead of expected increase.

**Link to the test files**: https://drive.google.com/drive/folders/1mlKVPvegU7P_ZQhj7veBAevAjMCss2qO?usp=sharing
The folder contains:
– .xlsx table with results of all tests.
– .txt file with full text of Program Error.
– Set 1, Set 2 and Set 3 pictures for the tests.

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
