### ISSUE TITLE
"View - Hide All/Show Hidden" menu item doesn't hide/show UI

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#75]
**Severity:** Minor
**Priority:** Medium

**Description:** Hiding/showing UI via menu doesn't change UI while Tab hotkey does.

**Steps to reproduce:**

1. Open Pixelitor.
2. Press Tab 3-5 times to make sure that UI hiding function works.
3. Click "View - Hide All/Show Hidden" menu item.

**Expected result:** UI changes.
**Actual result:** UI doesn't change.

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version (in a few days).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
