### ISSUE TITLE
Tiling with no opened windows throws exception

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#76]
**Severity:** Minor
**Priority:** Low

**Description:** When using "Internal Windows" in preferences "Arrange Windows" menu item is active even if there are no opened windows. "Tile" throws `java.lang.ArithmeticException: / by zero` while "Cascade" doesn't.

**Steps to reproduce:**

1. Open Pixelitor.
2. Click "Edit - Preferences".
3. In "Images In" dropdown select "Internal Windows".
4. Click "Close".
5. Click "View - Arrange Windows - Tile" menu item.

**Expected result:** Nothing happens.
**Actual result:** Exception `java.lang.ArithmeticException: / by zero` is thrown.

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
