### ISSUE TITLE
"New text layer" hotkey is active when there are no opened images

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#77]
**Severity:** Minor
**Priority:** Low

**Description:** When there are no opened images "Layer - Text Layer - New..." hotkey is active while menu item isn't. Pressing T throws `java.lang.IllegalStateException: no open image`.

**Steps to reproduce:**

1. Open Pixelitor.
2. Press T.

**Expected result:** Nothing happens.
**Actual result:** Exception `java.lang.IllegalStateException: no open image` is thrown.

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
