### ISSUE TITLE
"Zoom In" and "Zoom Out" hotkeys are active when there are no opened images

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#78]
**Severity:** Minor
**Priority:** Low

**Description:** When there are no opened images "View - Zoom - Zoom In" and "View - Zoom - Zoom Out" hotkeys are active while menu items aren't. Pressing Ctrl+Plus or Ctrl+Minus throws `java.lang.NullPointerException`.

**Steps to reproduce:**

1. Open Pixelitor.
2. Press Ctrl+Plus or Ctrl+Minus.

**Expected result:** Nothing happens.
**Actual result:** Exception `java.lang.NullPointerException` is thrown.

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version (in a few days).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
