### ISSUE TITLE
"Show Metadata" doesn't check existence of file

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#79]
**Severity:** Minor
**Priority:** Low

**Description:** "Show Metadata" doesn't check existence of file before reading metadata. Clicking "Show Metadata" when file is opened in Pixelitor but deleted from drive throws `java.io.FileNotFoundException` and `java.lang.NullPointerException`.

**Steps to reproduce:**

1. Open Pixelitor.
2. Open any image file.
3. Delete this file from drive.
4. Click "File - Show Metadata".

**Expected result:** Same warning is displayed as if you click "File - Reload".
**Actual result:** Exceptions `java.io.FileNotFoundException` and `java.lang.NullPointerException` are thrown.

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
