### ISSUE TITLE
Hotkeys are active in input fields in main window

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#80]
**Severity:** Major
**Priority:** High

**Description:** Typing text in input fields like "Layer Name", "Opacity", "Width", "Radius" etc. in main window triggers hotkeys. Windows like "Preferences" or "Resize" are not affected.

**Steps to reproduce:**

1. Open Pixelitor.
2. Create new image.
3. Double-click "layer 1" name.
4. Press X.

**Expected result:** Layer name in input field changes to "layer 1x".
**Actual result:** Layer name in input field changes to "layer1x", foreground and background colors are swapped. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version (in a few days).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
