### ISSUE TITLE
"Ctrl+O" selects next composition guide instead of opening file when Crop Tool is active

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#81]
**Severity:** Major
**Priority:** Medium

**Description:** Ctrl+O selects next composition guide instead of opening file when Crop Tool is active.

**Steps to reproduce:**

1. Open Pixelitor.
2. Press C.
3. Press Ctrl+O.

**Expected result:** "Open file" window appears.
**Actual result:** Next composition guide is selected. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
