### ISSUE TITLE
Deleting width/height when resizing by percentage throws exception

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#82]
**Severity:** Major
**Priority:** Medium

**Description:** Deleting all text in "Width" or "Height" input fields when resizing image by percentage throws `java.text.ParseException: Unparseable number`. Doesn't happen when resizing by pixels.

**Steps to reproduce:**

1. Open Pixelitor.
2. Create new image.
3. Press Ctrl+Alt+I.
4. Select "percent" in "Width" dropdown.
5. Delete all text in "Width" input field.

**Expected result:** Nothing happens.
**Actual result:** Exception `java.text.ParseException: Unparseable number` is thrown. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version (in a few days).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
