### ISSUE TITLE
Preferences: 0 is treated as positive number in "Undo/Redo Levels"

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#84]
**Severity:** Minor
**Priority:** Low

**Description:** "Undo/Redo Levels" must be positive integer but it can be set to 0.

**Steps to reproduce:**

1. Open Pixelitor.
2. Click "Edit - Preferences".
3. Delete "Undo/Redo Levels".
4. Click "Close".
5. Click "OK".
6. Set "Undo/Redo Levels" to 0.
7. Click "Close."

**Expected result:** Same warning is displayed.
**Actual result:** Preferences window is closed. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
I think this is a feature, not a bug :)
0 is a valid number for the number of undos. If you set it to 0, then you get 0, as you wanted.
