### ISSUE TITLE
Crop Tool: cropping outside of image throws exception if "Allow Growing" is unchecked

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#85]
**Severity:** Minor
**Priority:** Low

**Description:** Cropping outside of image throws `java.lang.IllegalArgumentException` exception if "Allow Grooming" is unchecked.

**Steps to reproduce:**

1. Open Pixelitor.
2. Create new image.
3. Press C.
4. Uncheck "Allow Growing".
5. Select area outside of image.
6. Click "Crop".

**Expected result:** Transparent image is cropped.
**Actual result:** Exception `java.lang.IllegalArgumentException` is thrown. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
This bug indeed exists in version 4.2.1, but it was already fixed in the development (GitHub) version.
The fix will be in the next released version (in a few days).

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
