### ISSUE TITLE
Opening nonexistent image throws exception

### ISSUE THREAD

**Issue by matnakash** [lbalazscs/Pixelitor#86]
**Severity:** Minor
**Priority:** Low

**Description:** Opening nonexistent image throws `java.lang.IllegalArgumentException` exception.

**Steps to reproduce:**

1. Open Pixelitor.
2. Press Ctrl+O.
3. Input name of nonexistent image, e.g. nonexistent.jpg (make sure it doesn't exist).
4. Click "Open".

**Expected result:** File is created and opened.
**Actual result:** Exception `java.lang.IllegalArgumentException` is thrown. 

**Environment:**

- **Pixelitor version:** 4.2.1
- **Java version:** 13.0.0.33
- **OS:** Windows 10 Version 1903 Build 18362.388

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version. (fixed by error dialog, and not creating new file, because it would not be clear what would be the size and contents of a default image )

**Comment by lbalazscs** [comment]
This bug is fixed in Pixelitor version 4.2.2, released today.
