### ISSUE TITLE
“Hue” at certain values adds artifacts to the image

### ISSUE THREAD

**Issue by BeVicky** [lbalazscs/Pixelitor#87]
**Pixelitor:** 4.2.1
**OS:** Windows 10 64 Bit
**Java Version:** 1.8.0_221

**Reproducibility:** Always
**Severity:** Minor
**Priority:** Medium
**Component:** Functional

**Description:** When “Hue” gets certain values there are some artifacts added to the image

**Steps to reproduce:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Open “Hue/Saturation” (Color -> Hue/Saturation)
4.	Enter any of “-140/-96/-80/-50/-40/-39/-32/-28/-24/-20/-16/-12/-8/-4” values to “Hue”
5.	Press "Enter"

**Expected result:** Hue changes without artifacts.
**Actual result:** Hue changes, artifacts are added to the image (Screenshots are attached).

Original Image (https://www.lifeofpix.com/photo/275-ake0260-jj-jpg/)
![275-ake0260-jj](https://user-images.githubusercontent.com/56333921/66467579-de855580-eaae-11e9-8dc0-83a03130857f.jpg)

Hue at -40 (Artifacts are market with red color)
![Hue -40](https://user-images.githubusercontent.com/56333921/66467642-f65cd980-eaae-11e9-8513-606b25a8c1cc.png)

Hue at -41 (No artifacts)
![Hue -41](https://user-images.githubusercontent.com/56333921/66467707-12607b00-eaaf-11e9-9268-918ed05882ac.png)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
Released in Pixelitor version 4.2.3.
