### ISSUE TITLE
"Ctrl+Z" does not work if rotate image with 2 or more layers

### ISSUE THREAD

**Issue by BeVicky** [lbalazscs/Pixelitor#89]
**Pixelitor:** 4.2.1
**OS:** Windows 10 64 Bit
**Java Version:** 1.8.0_221

**Reproducibility:** Always
**Severity:** Medium
**Priority:** High
**Component:** Functional

**Description:** If rotate image with 2 or more layers, "Undo" button isn’t active, "Ctrl+Z" doesn’t undo the action, as well.

**Steps to reproduce:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Add new layer (Layer -> Add New Layer)
4.	Rotate the image (Image -> Rotate (e.g., 90o CW))
5.	Press "Ctrl+Z"

**Expected result:** Rotation is cancelled.
**Actual result:** Nothing happens, image remains rotated

**Comment by lbalazscs** [comment]
This is indeed a problem, but it is basically the same issue #25
Currently operations that change multiple layers at the same time don't have undo. I intend to change this behavior, but I am closing this issue as I don't need multiple reminders.
