### ISSUE TITLE
"Reseed" button in "Sparkle" Filter does not have "Reseed" label

### ISSUE THREAD

**Issue by BeVicky** [lbalazscs/Pixelitor#90]
**Pixelitor:** 4.2.1
**OS:** Windows 10 64 Bit
**Java Version:** 1.8.0_221

**Reproducibility:** Always
**Severity:** Trivial
**Priority:** Low
**Component:** Visual

**Description:** "Reseed" button in "Sparkle" Filter does not have "Reseed" label unlike the same button in other filters.

**Steps to reproduce:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Open "Sparkle" Filter (Filter -> Light -> Sparkle)

**Expected result:** "Reseed" button has "Reseed" label
**Actual result:** "Reseed" button in "Sparkle" Filter does not have "Reseed" label

**Comment by lbalazscs** [comment]
This is a feature, not a bug :) The goal is to keep the width of the filter UI small. This is important on small screens, like laptops with 1366x768 resolution. Since the button is to the right of a large slider, the text would fit only if the whole
