### ISSUE TITLE
Max value is not present on multiple scale bars in "Filter"

### ISSUE THREAD

**Issue by BeVicky** [lbalazscs/Pixelitor#91]
**Reproducibility:** Always
**Severity:** Trivial
**Priority:** Low
**Component:** Visual

**Description:** Max value is not present on scale bars at many scale bars in "Filter"

**Steps to reproduce:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Open "Spar Blur" (Filter -> Blur/Sharpen -> Smart Blur)
4.	Go to "Threshold"

Other ways which contain the same defect (missing max value is in brackets):

1. Filter -> Blur/Sharpen -> Focus -> Focused Area Radius -> Horizontal (1,000)
2. Filter -> Blur/Sharpen -> Focus -> Focused Area Radius -> Vertical (1,000)
3. Filter -> Distort -> Swirl, Pinch, Bulge -> Radius (4,000)
4. Filter -> Distort -> Magnify -> Softness (999)
5. Filter -> Distort -> Turbulent Distortion -> Amount (280)
6. Filter -> Distort -> Water Ripple -> Radius (4,000)
7. Filter -> Distort -> Water Ripple -> Wave Length (1,000)
8. Filter -> Distort -> Waves -> Wavelength -> Horizontal (800)
9. Filter -> Distort -> Waves -> Wavelength -> Vertical (800)
10. Filter -> Distort -> Angular Waves -> Radial Wavelength (200)
11. Filter -> Distort -> Frosted Glass -> Amount (400)
12. Filter -> Distort -> Wrap Around Arc -> Divide Angle (24)
13. Filter -> Dislocate -> Slice -> Size (1,000)
14. Filter -> Dislocate -> Video Feedback -> Zoom (-5)
15. Filter -> Light -> Flashlight -> Radius -> Horizontal (4,000)
16. Filter -> Light -> Flashlight -> Radius -> Vertical (4,000)
17. Filter -> Light -> Sparkle -> High Intensity Radius (4,000)

**Expected result:** Max value (255) is present on "Threshold" scale bar
**Actual result:** Max value (255) is missing on "Threshold" scale bar (Screenshot of one example is attached) - Missing value is marked with red color

![Missing number](https://user-images.githubusercontent.com/56333921/66481127-6af14180-eaca-11e9-8a25-46ae42fae268.png)

**Comment by lbalazscs** [comment]
Fixed in GitHub, it will be in the next released version.

**Comment by lbalazscs** [comment]
Fixed in Pixelitor version 4.2.3, released today.
