### ISSUE TITLE
"Crop Selection" does not work properly for selections of any shapes except rectangular

### ISSUE THREAD

**Issue by BeVicky** [lbalazscs/Pixelitor#92]
**Pixelitor:** 4.2.1
**OS:** Windows 10 64 Bit
**Java Version:** 1.8.0_221

**Reproducibility:** Always
**Severity:** Medium
**Priority:** High
**Component:** Functional

**Description:** If create selection of any shape except rectangular and crop selection, selection is cropped as rectangular instead of initially created shape.

**Steps to reproduce:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Use "Selection Tool" to select an area on the image
4.	Choose "Add/Subtract/Intersect" in "New Selection" dropdown menu (Selection Tool -> New Selection)
5.	Select another area on the image that is partly overlays the first selection to create selection of any shape except rectangular
6.	Click "Crop Selection"

**Alternative steps:**
1.	Run Pixelitor
2.	Open new image (Ctrl+O)
3.	Use "Shapes Tool" to draw any shape (e.g., Heart)
4.	Click "Convert to Selection"
5.	Click "Crop Selection"

**Expected result:** A selection is cropped as "Heart" shape.
**Actual result:** A selection is cropped as rectangular.

**Comment by lbalazscs** [comment]
Well, cropping means creating a smaller image and all images have to be rectangular, although they can also contain transparent pixels. I guess I could treat this as a feature request to optionally also hide parts of the image with layer masks.

**Comment by lbalazscs** [comment]
Implemented in GitHub, it will be in the next released version. 
![selcropmessage](https://user-images.githubusercontent.com/9939454/66717074-51573f00-edd5-11e9-9a9d-2e11fcf771fa.png)

**Comment by lbalazscs** [comment]
Released in Pixelitor version 4.2.3.
