### ISSUE TITLE
Copy Composite ignores selection

### ISSUE THREAD

**Issue by jEsuSdA** [lbalazscs/Pixelitor#98]
I found a behavior that I think could be a possible bug or may be a behavior that I don't understand very well. :D  

Step to reproduce:

1. Create a new image
2. Paint something in the main layer
3. Create a new layer
4. Paint something in the new layer
5. Make a rectangular selection
6. Edit > Copy Composite
7. Edit > Paste as new Image

Expected behavior: A new image with the selected contend that include all layers of the original image.

Actual behavior: A merged copy of the entire original image.

Thanks a lot!!!

**Comment by lbalazscs** [comment]
Composite means to me the resulting image after all the layers have been blended/merged together. Even you translated it as Copiar Visible, and I assume "visible" means the same as in English: what you see and nothing more... Basically this functionality is for copying the result image into another program, which might not even have the concept of layers.

If you want a new image with the selected content that includes all layers of the original image, you can do Image/Duplicate to create a copy with all the layers, and then in the Selection tool press "Crop Selection", and then you see a question that explains that even "selected content" could mean multiple things...

Possibly Copy Composite should not ignore the selection, I'm not sure if it is even possible to put transparent pixels on the clipboard, I'll check this and think about it.

**Comment by jEsuSdA** [comment]
Ok. I understand. So, I should think about translation to "copiar visible" is the best translation possible. :D
Thanks for the explanation. ;)

**Comment by lbalazscs** [comment]
I checked in Gimp, and this functionality is called "Copy Visible" (in the English version). Maybe I will also rename it in Pixelitor, as "composite" can be easily confused with "composition". And yes, it should not ignore the selection. What Gimp does (a crop with the bounding rectangle and setting the remaining unselected pixels to transparent ) makes sense, so I guess we can agree that this is the expected behavior if there is a selection.

**Comment by lbalazscs** [comment]
I committed a new version to GitHub that should fix this bug: the copied image should take the selection into account, and for nonrectangular selections it should set the unselected pixels to transparent (same as Gimp). The copied image is flattened (has only one layer).

**Comment by lbalazscs** [comment]
Fixed in https://github.com/lbalazscs/Pixelitor/releases/tag/v4.2.4-beta1

**Comment by lbalazscs** [comment]
Fixed in the just released 4.3.0
